import type { Metadata } from "next";
import "../globals.css";
import Nav from "../components/Nav";
import { GlobalProvider } from "../context/GlobalContext";

export const metadata: Metadata = {
  title: "Souq7",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"}>
      <GlobalProvider>
        <body className={` ${lang === "ar" ? "font-graphik-arabic font-medium" : "font-Poppins" } relative`}>
          <img className="absolute top-0 left-0" src="/gradien.svg" alt="" />
          <img
            className="absolute bottom-[-300px] right-0"
            src="/gradien-2.svg"
            alt=""
            />
          <Nav />
        
          {children}
        </body>
      </GlobalProvider>
    </html>
  );
}
